language: objective-c
osx_image: xcode7.2
branches: 
    only:
        - master
script:
- xctool -project ./SampleProject/SampleProject.xcodeproj -scheme SampleProject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Release OBJROOT=$PWD/build CONFIGURATION_BUILD_DIR=$PWD/build SYMROOT=$PWD/build
env:
  global:
  - APP_NAME="SampleProject"
before_deploy:
- zip -r --symlinks "$APP_NAME-$TRAVIS_TAG.zip" "$PWD/build/$APP_NAME.app"
deploy:
    provider: releases
    script: scripts/deploy.sh
    api_key: d94688f50bddcfca80cdee6006a4560e4fb1de91
    file: '$APP_NAME-$TRAVIS_TAG.zip'
    skip_cleanup: true
    on:
        repo: upradeepk/TravisTesting
        branch: master
        tags: true
